version: '2'
services:

      beerblog_server:
        build: ./BeerBlog/BeerBlog/
        ports: 
          - 8083:8000
        depends_on:
          - mongodb_beerblog
        volumes:
          - ./BeerBlog/BeerBlog/photo:/app/photo
        environment:
          WAIT_HOSTS: mongodb_beerblog:27017

      mongodb_beerblog:
        image: mongo:latest
        container_name: mongodb_beerblog
        environment:
          - MONGODB_USER="user" 
          - MONGODB_PASS="pass"
        volumes:
          - ./BeerBlog/BeerBlog/data/db:/data/db
        command: mongod


      # admin_server:
      #   build: ./admin/admin/
      #   ports: 
      #     - 8082:8000
      #   depends_on:
      #     - mongodb_auth
      #   environment:
      #     WAIT_HOSTS: mongodb_auth:27017


      # auth_server:
      #   build: ./auth/auth/
      #   ports: 
      #     - 8081:8080
      #   depends_on:
      #     - mongodb_auth
      #   environment:
      #     WAIT_HOSTS: mongodb_auth:27017

      # mongodb_auth:
      #   image: mongo:latest
      #   container_name: mongodb_auth
      #   environment:
      #     - MONGODB_USER="user" 
      #     - MONGODB_PASS="pass"
      #   volumes:
      #     - ./auth/auth/data/db:/data/db
      #   command: mongod

